name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy code on server
    runs-on: ubuntu-latest
    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: 'github@prohorovka.itgrco.com'
          privateKey: ${{ secrets.DEPLOY_ITG_KEY }}
          command: sudo docker exec tb-stage.iot-rt.ru /usr/bin/ssh-agent bash -c 'ssh-add /root/.ssh/gh_deploy; cd /app/bundle; git pull origin main'

